
transform : transform.py
	python transform.py -s ../../ftrl_tr.csv -d fm_tr.csv -t train
	python transform.py -s ../../ftrl_te.csv -d fm_te.csv -t test
	python transform.py -s ../../ftrl_de.csv -d fm_de.csv -t dev
